version: '3'
services:
  timemachine:
    hostname: TimeMachine
    secrets:
      - timemachine-password
    environment:
      - PASSWORD_FILE=/run/secrets/timemachine-password
      #- PASSWORD=timemachine
      #- LOG_LEVEL=3
      - CUSTOM_AFP_CONF=false
      #- MIMIC_MODEL=TimeCapsule6,106
      - MIMIC_MODEL=TimeCapsule8,119
      - TM_USERNAME=timemachine
      - TM_GROUPNAME=timemachine
      - TM_UID=1000
      - TM_GID=1000
      - SET_PERMISSIONS=false
      - VOLUME_SIZE_LIMIT=0
    restart: unless-stopped
    volumes:
      - ./data:/opt/timemachine
      - timemachine-netatalk:/var/netatalk
      - timemachine-logs:/var/log/supervisor
      - ./zerotier-one:/var/lib/zerotier-one
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
    container_name: timemachine
    image: plbertrand/zerotier-timemachine:latest

secrets:
  timemachine-password:
    file: timemachine-password.txt

volumes:
  timemachine-netatalk:
  timemachine-logs:
